adds second kuksa client in zenoh-kuksa-provider
eclipse-kuksa/kuksa-incubation pull request #10
Opened 2024-10-15 17:23 UTC by eriksven

To avoid  a deadlock between waiting for the kuksa subscription and sending messages on the same client, a second client gets initialized. In addition, some clippy warning get fixed.

2024-10-15 17:25 UTC, eriksven commented
@max-grzanna what do you think?

2024-10-15 17:31 UTC, eriksven commented
I ran into a deadlock where the task with the function `publish_to_zenoh` could not acquire the lock for the kuksa_client because it seems to be locked by the the other task with the `handling_zenoh_subscription` . There is most likely a better solution, but my quick fix here now, is now to instantiate a second kuksa_client. 

The approach of locking the client whenever one actually wants to send something might fall short too, when the kuksa_client is occupied by waiting on the subscription in the `publish_to_zenoh` (currently line 115 in main.rs). Because we obviously do not want that the `handling_zenoh_subscription` has to wait for a new incoming messages before being able to acquire the lock to execute `set_current_values` when required.

2024-10-21 14:01 UTC, max-grzanna commented
Instantiating a second client works for me. I can't think of a better option either.

2024-10-21 14:03 UTC, max-grzanna approved these changes

2024-10-21 14:04 UTC, max-grzanna reviewed
LGTM

2024-10-21 16:11 UTC, lukasmittag requested changes
Minor comments

2024-10-21 16:11 UTC, lukasmittag commented on zenoh-kuksa-provider/Cargo.toml
> +
not needed

2024-10-21 16:11 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +            drop(sub_client);
can be removed if the function ends it will be dropped anyways
```suggestion
```

2024-10-21 16:11 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +    match kuksa_client.subscribe_target_values(vss_paths).await {
why this change?

2024-10-21 16:11 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +                                let buf = match datapoint_to_string(datapoint) {
please keep using the reference

2024-10-21 16:11 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +    let actuation_client = kuksa::Client::new(uri);
why use two clients here?

2024-10-21 16:23 UTC, lukasmittag commented
I think dropping the sub_client in the `handle_zenoh_subscription` should solve the issue already. https://fongyoong.github.io/easy_rust/Chapter_43.html If thats not the case please let me know

2024-10-21 16:32 UTC, lukasmittag commented
Okay, might not solve it entirely since you're blocking with a while loop after subscribing to databroker. As you described not what you want yes so keep using two clients in this case. Nonetheless some comments about the implementation.

2024-10-21 16:37 UTC, lukasmittag requested changes

2024-10-21 16:37 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
>      fetch_metadata(
since you await this function you do not need to have a
 ```
let client = Arc::new(Mutex::new(kuksa::Client::new(uri.clone())));
```

2024-10-21 16:37 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +    let client = Arc::new(Mutex::new(kuksa::Client::new(uri.clone())));
let client = kuksa::Client::new(uri.clone());

2024-10-21 16:37 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
>          client.clone(),
use a reference here instead

2024-10-21 16:37 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +    mut kuksa_client: kuksa::Client,
use reference. mut not needed since you're not editing the client

2024-10-21 16:37 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
>  ) {
use reference for kuksa_client

2024-10-25 12:33 UTC, max-grzanna commented on zenoh-kuksa-provider/src/main.rs
> +    mut kuksa_client: kuksa::Client,
I think it is necessary to have a mutable client because the implementation for the functions requires a mutable reference for _self_. 

```
    pub async fn subscribe_target_values(
        &mut self,
        paths: Vec<&str>,
```

Correct me if I'm wrong.

2024-10-25 20:09 UTC, eriksven commented
@lukasmittag I pushed a new commit, could you please have another look at some time. Sorry for the delay, I was on business trip this week.

2024-10-28 09:20 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +    mut kuksa_client: kuksa::Client,
Will check if `mut` is necessary there, but yes you're right. Nice catch!

2024-10-30 14:06 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +    mut kuksa_client: kuksa::Client,
I've checked it is necessary so all good here

2024-10-30 14:06 UTC, lukasmittag commented on zenoh-kuksa-provider/src/utils/kuksa_utils.rs
> +) -> Client {
you should not return anything here right?

2024-10-30 14:06 UTC, lukasmittag commented on zenoh-kuksa-provider/src/utils/kuksa_utils.rs
> +    kuksa_client
unnecessary to return this

2024-10-30 14:06 UTC, lukasmittag commented on zenoh-kuksa-provider/src/main.rs
> +        client,
should work if you give a reference or clone the client

2024-11-04 09:52 UTC, lukasmittag approved these changes
good enough to be merged. Note: TODO - check if mutable is really necessary in rust lib of kuksa

2024-11-04 12:21 UTC, merged