Erik persist
eclipse-kuksa/kuksa-incubation pull request #13
Opened 2024-11-06 13:56 UTC by erikbosch

2024-12-04 12:54 UTC, SebastianSchildt commented
@MathiasDanzeisen is this functional, and  includes everything you intended to have here? Or do we need to extend this? If so, should we merge already, and add further PRs as required?

2024-12-05 12:44 UTC, MathiasDanzeisen requested changes
Thanks for putting up the pull request.
I suggested some changes in the Cargo script to build the demo without the djson lib at hand and improvements for documentation

2024-12-05 12:44 UTC, MathiasDanzeisen commented on kuksa-persistence-provider/Cargo.toml
> +json_djson = [ "dep:djson","dep:tinyjson"  ]
```suggestion
# json_djson = [ "dep:djson","dep:tinyjson"  ] # Uncomment to use djson lib
```

2024-12-05 12:44 UTC, MathiasDanzeisen commented on kuksa-persistence-provider/Cargo.toml
> +djson = { path="../../platform/modules/json-al/djson_rust/" ,  optional = true }
```suggestion
# djson = { path="../../platform/modules/json-al/djson_rust/" ,  optional = true } # Uncomment to use djson lib
```

2024-12-05 12:44 UTC, MathiasDanzeisen commented on kuksa-persistence-provider/Readme.md
> +  Check out the repo with the depenable json library at the same level as the parent folder or project folder of this repo.
```suggestion
  * Check out the repo with the depenable json library at the same level as the parent folder or project folder of this repo.
```

2024-12-05 12:44 UTC, MathiasDanzeisen commented on kuksa-persistence-provider/Readme.md
> +  Enable with ```cargo build --features json_djson --no-default-features```
```suggestion
  * Edit `Cargo.toml` and uncomment the following lines

    ```toml
    djson = { path="../../platform/modules/json-al/djson_rust/" ,  optional = true } # Uncommment to use djson

    # ... 

    json_djson = [ "dep:djson","dep:tinyjson"  ]   # Uncommment to use djson
    ```
  * Install rust nightly which is needed for djson at the moment [11/2024]
    ```bash
    rustup toolchain install nightly
    rustup default nightly
    ```
  * Enable with ```cargo build --features json_djson --no-default-features``````

2024-12-05 12:44 UTC, MathiasDanzeisen commented on kuksa-persistence-provider/Readme.md
> +```
```suggestion

1) Check for empty data point after startup
   
    * In Terminal A): Start kuksa databroker with:

        ```bash
        docker run -it --rm --net=host ghcr.io/eclipse-kuksa/kuksa-databroker:latest --port 55556
        ```

    * In Terminal B) Start kuksa sdk with:

        ```bash
        docker run -it --rm --net=host ghcr.io/eclipse-kuksa/kuksa-python-sdk/kuksa-client:latest grpc://127.0.0.1:55556
        # Check Vales in cmd
        getValue Vehicle.Cabin.HVAC.Station.Row4.Passenger.FanSpeed
        ```

    * In Terminal C) Start kuksa persistency provider with:

        ```bash
        cargo run
        ```

2) Set data point which is stored by persistency provider
    * In Terminal B) :

        ```bash
        # Set Vales in cmd
        setValue Vehicle.Cabin.HVAC.Station.Row4.Passenger.FanSpeed 40
        ```
3) Restart and check if datapoint with old value is restored by persistency provider
```

2024-12-05 12:44 UTC, MathiasDanzeisen commented on kuksa-persistence-provider/Readme.md
> +```
```suggestion

```bash
cargo build 
# with features, see above for prerequisites
cargo build --features json_djson --no-default-features
```
```

2024-12-05 16:33 UTC, SebastianSchildt approved these changes
Thank you for providing/fixing this.

Merging this now. Once djson location is stable we can revisit, and add the URL.

2024-12-05 16:34 UTC, merged